# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ml.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'ml.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08ml.proto\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x14\n\x05Hello\x12\x0b\n\x03res\x18\x01 \x01(\t\"\x1f\n\x0fSymptomsRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"F\n\x07Symptom\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0b\n\x03loc\x18\x03 \x01(\t\x12\x12\n\nconfidence\x18\x04 \x01(\x02\x32_\n\x0cTokensServer\x12,\n\x0c\x46indSymptoms\x12\x10.SymptomsRequest\x1a\x08.Symptom0\x01\x12!\n\x08SayHello\x12\r.HelloRequest\x1a\x06.Hellob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ml_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HELLOREQUEST']._serialized_start=12
  _globals['_HELLOREQUEST']._serialized_end=40
  _globals['_HELLO']._serialized_start=42
  _globals['_HELLO']._serialized_end=62
  _globals['_SYMPTOMSREQUEST']._serialized_start=64
  _globals['_SYMPTOMSREQUEST']._serialized_end=95
  _globals['_SYMPTOM']._serialized_start=97
  _globals['_SYMPTOM']._serialized_end=167
  _globals['_TOKENSSERVER']._serialized_start=169
  _globals['_TOKENSSERVER']._serialized_end=264
# @@protoc_insertion_point(module_scope)
