# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transcribe.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'transcribe.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10transcribe.proto\"h\n\tAudioFile\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0e\n\x06\x66ormat\x18\x02 \x01(\t\x12\x13\n\x0bsample_rate\x18\x03 \x01(\r\x12\x10\n\x08\x63hannels\x18\x04 \x01(\r\x12\x12\n\naudio_data\x18\x05 \x01(\x0c\"L\n\x17HindiTranscribeResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x10\n\x08original\x18\x03 \x01(\t\"5\n\x12TranscribeResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t2\x84\x01\n\x0c\x41udioService\x12\x34\n\x0fTranscribeAudio\x12\n.AudioFile\x1a\x13.TranscribeResponse(\x01\x12>\n\x14HindiTranscribeAudio\x12\n.AudioFile\x1a\x18.HindiTranscribeResponse(\x01\x42-Z+github.com/newtoallofthis123/patients/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transcribe_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z+github.com/newtoallofthis123/patients/types'
  _globals['_AUDIOFILE']._serialized_start=20
  _globals['_AUDIOFILE']._serialized_end=124
  _globals['_HINDITRANSCRIBERESPONSE']._serialized_start=126
  _globals['_HINDITRANSCRIBERESPONSE']._serialized_end=202
  _globals['_TRANSCRIBERESPONSE']._serialized_start=204
  _globals['_TRANSCRIBERESPONSE']._serialized_end=257
  _globals['_AUDIOSERVICE']._serialized_start=260
  _globals['_AUDIOSERVICE']._serialized_end=392
# @@protoc_insertion_point(module_scope)
